### ISSUE TITLE
Background image takes too long to load in mobile

### ISSUE THREAD

**Issue by kevcomedia** [kevcomedia/fcc-portfolio#4]
The portfolio uses one large image for background. Maybe make the default background image a small one, then add a media query for larger screens. Something like
```css
body {
  background-image: url('smaller.jpg');
}

@media(min-width: 700px) {
  body {
    background-image: url('larger.jpg');
  }
}
```
